[bug][add]fix some bugs and add some samples
RT-Thread-packages/bsal pull request #7
Opened 2021-10-10 03:36 UTC by WaterFishJ

[bug]fix uart sample bug
[bug]fix get start handle bug
[bug]fix the reg_service bug
[add]add LED Button Service, Device Information Service
[add]HRS, LBS sample
[bug]fix gnu option
以上是 Summer 2021 项目时的一些贡献，涉及一些文件的修改与增添，劳烦检查与合并

2021-10-10 11:26 UTC, supperthomas requested changes

2021-10-10 11:26 UTC, supperthomas commented on profiles/service/bsal_dis/bsal_srv_dis.c
> +    bsal_stack_le_srv_reg_func(stack_ptr, &ble_svc_hid_defs, (P_SRV_GENERAL_CB *)dis_profile_callback);
ble_svc_hid_defs?

2021-10-10 11:26 UTC, supperthomas commented on profiles/service/bsal_uart/bsal_srv_uart.c
> +int bsal_bleuart_init(void *stack_ptr, uint16_t *conn_id)
uint16_t *conn_id
这里用指针的目的是什么呢？

2021-10-10 11:30 UTC, supperthomas commented
@WaterFishJ readme.md请帮忙添加您的相关帮助文档，谢谢。

2021-10-10 12:15 UTC, WaterFishJ commented on profiles/service/bsal_uart/bsal_srv_uart.c
> +int bsal_bleuart_init(void *stack_ptr, uint16_t *conn_id)
> uint16_t *conn_id 这里用指针的目的是什么呢？

这条函数在 sample 中初始化时只调用一次，若不使用指针，则会由于初始化时没有设备连接，connect id 为空

2021-10-10 14:11 UTC, supperthomas commented
+2

2021-10-11 01:16 UTC, supperthomas approved these changes

2021-10-11 01:38 UTC, merged